// Generated by https://pagedraw.io/pages/11802
import React from 'react';
import './webframe.css';


export default class Webframe extends React.Component {
  render() {
    return (
      <div className="webframe-webframe-0">
          <div className="webframe-0">
              <div className="webframe-frameshoeshopp-0">
                  <div className="webframe-0-0-0">
                      <div className="webframe-title-0">
                          <div className="webframe-0-0-0-0-0">
                              <div className="webframe-the_shoes_shopping_store-0">
                                  The Shoes Shopping Store
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-0-1">
                  <div className="webframe-0-1-0">
                      <div className="webframe-0-1-0-0">
                          <div className="webframe-shoesel-0" /> 
                          <div className="webframe-frameshoeselect-0">
                              <div className="webframe-0-1-0-0-1-0">
                                  <div className="webframe-shoe_selections-0">
                                      Shoe Selections
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-framecheckout-0">
                  <div className="webframe-0-2-0">
                      <div className="webframe-checkout-0">
                          <div className="webframe-0-2-0-0-0">
                              <div className="webframe-cart_checkout-0">
                                  Cart Checkout
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-1">
              <div className="webframe-1-0">
                  <div className="webframe-1-0-0">
                      <div className="webframe-frame-0">
                          <div className="webframe-1-0-0-0-0">
                              <div className="webframe-cardbox-0">
                                  <div className="webframe-1-0-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/1193d260-9c6a-431d-8a93-b753d95b5b0e/" className="webframe-image_2" /> 
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-1">
                                      <div className="webframe-price-0">
                                          <div className="webframe-1-0-0-0-0-0-1-0-0">
                                              <div className="webframe-_4">$40.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframe-1-0-0-0-0-0-2">
                                      <div onClick={this.props.onClick} className="webframe-addtocart-0" style={{"background": this.props.color}}>
                                          <div className="webframe-1-0-0-0-0-0-2-0-0">
                                              <div className="webframe-add_to_cart-0">Add to Cart</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframe-1-1">
                  <div className="webframe-1-1-0">
                      <div className="webframe-framecard2">
                          <div className="webframe-1-1-0-0-0">
                              <div className="webframe-cardbox-00">
                                  <div className="webframe-1-1-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/2dc36991-42f3-4dde-9356-9f101b928541/" className="webframe-image-0" /> 
                                  </div>
                                  <div className="webframe-1-1-0-0-0-0-1">
                                      <div className="webframe-price-00">
                                          <div className="webframe-1-1-0-0-0-0-1-0-0">
                                              <div className="webframe-_3">$30.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframe-1-1-0-0-0-0-2">
                                      <div onClick={this.props.addToCart2} className="webframe-addtocart-00" style={{"cursor": (this.props.text2)}}>
                                          <div className="webframe-1-1-0-0-0-0-2-0-0">
                                              <div className="webframe-add_to_cart-00">Add to Cart</div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-2">
              <div className="webframe-frame_2">
                  <div className="webframe-2-0-0">
                      <div className="webframe-rectangle-0">
                          <div className="webframe-2-0-0-0-0">
                              <img src="https://ucarecdn.com/90eb3b85-892d-48e7-897e-f1f79d3cad9a/" className="webframe-image_3" /> 
                          </div>
                      </div>
                  </div>
                  <div className="webframe-2-0-1">
                      <div onChange={this.props.handleChange} className="webframe-carttotalbox-0">
                          <div className="webframe-2-0-1-0-0">
                              <div className="webframe-type_something_-6">
                                  { this.props.text }
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframe-3" /> 
      </div>
    );
  }
};
