// Generated by https://pagedraw.io/pages/11802
import React from 'react';
import './webframeheadless.css';


export default class Webframeheadless extends React.Component {
  render() {
    return (
      <div className="webframeheadless-webframeheadless-5">
          <div className="webframeheadless-0">
              <div className="webframeheadless-0-0">
                  <div className="webframeheadless-0-0-0">
                      <div className="webframeheadless-frame-0">
                          <div className="webframeheadless-0-0-0-0-0">
                              <div className="webframeheadless-cardbox-1">
                                  <div className="webframeheadless-0-0-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/1193d260-9c6a-431d-8a93-b753d95b5b0e/" className="webframeheadless-image_2" /> 
                                  </div>
                                  <div className="webframeheadless-0-0-0-0-0-0-1">
                                      <div className="webframeheadless-price-0">
                                          <div className="webframeheadless-0-0-0-0-0-0-1-0-0">
                                              <div className="webframeheadless-_4">$40.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframeheadless-0-0-0-0-0-0-2">
                                      <div onClick={this.props.onClick} className="webframeheadless-addtocart-2">
                                          <div className="webframeheadless-0-0-0-0-0-0-2-0-0">
                                              <div className="webframeheadless-add_to_cart-0">
                                                  Add to Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div className="webframeheadless-0-1">
                  <div className="webframeheadless-0-1-0">
                      <div className="webframeheadless-framecard2">
                          <div className="webframeheadless-0-1-0-0-0">
                              <div className="webframeheadless-cardbox-12">
                                  <div className="webframeheadless-0-1-0-0-0-0-0">
                                      <img src="https://ucarecdn.com/2dc36991-42f3-4dde-9356-9f101b928541/" className="webframeheadless-image-4" /> 
                                  </div>
                                  <div className="webframeheadless-0-1-0-0-0-0-1">
                                      <div className="webframeheadless-price-00">
                                          <div className="webframeheadless-0-1-0-0-0-0-1-0-0">
                                              <div className="webframeheadless-_3">$30.00</div>
                                          </div>
                                      </div>
                                  </div>
                                  <div className="webframeheadless-0-1-0-0-0-0-2">
                                      <div onClick={this.props.addToCart2} className="webframeheadless-addtocart-3">
                                          <div className="webframeheadless-0-1-0-0-0-0-2-0-0">
                                              <div className="webframeheadless-add_to_cart-4">
                                                  Add to Cart
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframeheadless-1">
              <div className="webframeheadless-frame_2">
                  <div className="webframeheadless-1-0-0">
                      <div className="webframeheadless-rectangle-0">
                          <div className="webframeheadless-1-0-0-0-0">
                              <img src="https://ucarecdn.com/90eb3b85-892d-48e7-897e-f1f79d3cad9a/" className="webframeheadless-image_3" /> 
                          </div>
                      </div>
                  </div>
                  <div className="webframeheadless-1-0-1">
                      <div onChange={this.props.handleChange} className="webframeheadless-carttotalbox-7">
                          <div className="webframeheadless-1-0-1-0-0">
                              <div className="webframeheadless-type_something_-9">
                                  { this.props.text }
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <div className="webframeheadless-2" /> 
      </div>
    );
  }
};
